name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  Release:
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    # https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          # a special token in github at the organization account level
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # first must use the Datateer account token, then after first publish can generate a repo-specific token
          pypi_token: ${{ secrets.PYPI_TOKEN }}
